export const GET_TOTAL_CHART_REQUEST = "GET_TOTAL_CHART_REQUEST";
export const GET_TOTAL_CHART_RECEIVE = "GET_TOTAL_CHART_RECEIVE";
export const GET_TOTAL_CHART_ERROR = "GET_TOTAL_CHART_ERROR";

export const GET_SPEC_SITE_CHART_REQUEST = "GET_SPEC_SITE_CHART_REQUEST";
export const GET_SPEC_SITE_CHART_RECEIVE = "GET_SPEC_SITE_CHART_RECEIVE";
export const GET_SPEC_SITE_CHART_ERROR = "GET_SPEC_SITE_CHART_ERROR";

export const GET_SPEC_WIDGET_CHART_REQUEST = "GET_SPEC_WIDGET_CHART_REQUEST";
export const GET_SPEC_WIDGET_CHART_RECEIVE = "GET_SPEC_WIDGET_CHART_RECEIVE";
export const GET_SPEC_WIDGET_CHART_ERROR = "GET_SPEC_WIDGET_CHART_ERROR";

export const GET_SPEC_POST_CHART_REQUEST = "GET_SPEC_POST_CHART_REQUEST";
export const GET_SPEC_POST_CHART_RECEIVE = "GET_SPEC_POST_CHART_RECEIVE";
export const GET_SPEC_POST_CHART_ERROR = "GET_SPEC_POST_CHART_ERROR";
