export const GET_POSTS_LIST_REQUEST = "GET_POSTS_LIST_REQUEST";
export const GET_POSTS_LIST_RECEIVE = "GET_POSTS_LIST_RECEIVE";
export const GET_POSTS_LIST_ERROR = "GET_POSTS_LIST_ERROR";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_RECEIVE = "CREATE_POST_RECEIVE";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const GET_POST_DETAILS_REQUEST = "GET_POST_DETAILS_REQUEST";
export const GET_POST_DETAILS_RECEIVE = "GET_POST_DETAILS_RECEIVE";
export const GET_POST_DETAILS_ERROR = "GET_POST_DETAILS_ERROR";

export const GET_POST_DETAILS_STATS_PROMO_REQUEST =
  "GET_POST_DETAILS_STATS_PROMO_REQUEST";
export const GET_POST_DETAILS_STATS_PROMO_RECEIVE =
  "GET_POST_DETAILS_STATS_PROMO_RECEIVE";
export const GET_POST_DETAILS_STATS_PROMO_ERROR =
  "GET_POST_DETAILS_STATS_PROMO_ERROR";

export const UPDATE_POST_DETAILS_REQUEST = "UPDATE_POST_DETAILS_REQUEST";
export const UPDATE_POST_DETAILS_RECEIVE = "UPDATE_POST_DETAILS_RECEIVE";
export const UPDATE_POST_DETAILS_ERROR = "UPDATE_POST_DETAILS_ERROR";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_RECEIVE = "DELETE_POST_RECEIVE";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";
