export const GET_WIDGETS_LIST_REQUEST = 'GET_WIDGETS_LIST_REQUEST';
export const GET_WIDGETS_LIST_RECEIVE = 'GET_WIDGETS_LIST_RECEIVE';
export const GET_WIDGETS_LIST_ERROR = 'GET_WIDGETS_LIST_ERROR';

export const CREATE_WIDGET_REQUEST = 'CREATE_WIDGET_REQUEST';
export const CREATE_WIDGET_RECEIVE = 'CREATE_WIDGET_RECEIVE';
export const CREATE_WIDGET_ERROR = 'CREATE_WIDGET_ERROR';

export const GET_WIDGET_DETAILS_REQUEST = 'GET_WIDGET_DETAILS_REQUEST';
export const GET_WIDGET_DETAILS_RECEIVE = 'GET_WIDGET_DETAILS_RECEIVE';
export const GET_WIDGET_DETAILS_ERROR = 'GET_WIDGET_DETAILS_ERROR';

export const UPDATE_WIDGET_DETAILS_REQUEST = 'UPDATE_WIDGET_DETAILS_REQUEST';
export const UPDATE_WIDGET_DETAILS_RECEIVE = 'UPDATE_WIDGET_DETAILS_RECEIVE';
export const UPDATE_WIDGET_DETAILS_ERROR = 'UPDATE_WIDGET_DETAILS_ERROR';

export const DELETE_WIDGET_REQUEST = 'DELETE_WIDGET_REQUEST';
export const DELETE_WIDGET_RECEIVE = 'DELETE_WIDGET_RECEIVE';
export const DELETE_WIDGET_ERROR = 'DELETE_WIDGET_ERROR';